#!/bin/sh

# Called by "git commit" with no arguments.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the commit.
#
# NOTE: Part of this file is derived from .git/hooks/pre-commit.sample

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr
exec 1>&2

# If there are whitespace errors, print the offending file names and fail
git diff-index --check --cached $against -- || exit $?

# If clang-format is installed, run it now
if [ -x /usr/bin/git-clang-format ]; then
    git clang-format --binary /usr/bin/clang-format-12 --quiet --diff || exit $?
fi
