variables:
  DEBIAN_IMAGE: "registry.gitlab.com/goodvibes/goodvibes/debian:sid"
  FEDORA_IMAGE: "registry.gitlab.com/goodvibes/goodvibes/fedora:latest"

debian-gcc:
  image: $DEBIAN_IMAGE
  stage: build
  script:
    - .gitlab-ci/build.sh

debian-clang:
  image: $DEBIAN_IMAGE
  stage: build
  only: [ tags ]
  variables:
    CC: clang
  script:
    - .gitlab-ci/build.sh

fedora-gcc:
  image: $FEDORA_IMAGE
  stage: build
  only: [ tags ]
  script:
    - .gitlab-ci/build.sh

fedora-clang:
  image: $FEDORA_IMAGE
  stage: build
  only: [ tags ]
  variables:
    CC: clang
  script:
    - .gitlab-ci/build.sh

debian-gcc-no-ui:
  image: $DEBIAN_IMAGE
  stage: build
  only: [ tags ]
  script:
    - .gitlab-ci/build.sh -Dui-enabled=false

debian-gcc-no-feat-hotkeys:
  image: $DEBIAN_IMAGE
  stage: build
  only: [ tags ]
  script:
    - .gitlab-ci/build.sh -Dfeat-hotkeys=false
